const HOME_PAGE_URL = '/home';
const LOGIN_PAGE_URL = '/login';
const SIGNUP_PAGE_URL = '/sign-up';
const PERSONAL_PAGE_URL = '/personal';
const CATEGORY_PAGE_URL = '/category/:code';

const ROLE_ADMIN = 'ROLE_ADMIN';
const ROLE_USER = 'ROLE_USER';

const API_BASE_URL = 'http://192.168.1.4:8083';
const LOCAL_STORAGE_NAME = 'ecormerce_ctu';

const ACTION_GET_USER_INFO = 'ACTION_GET_USER_INFO';
const ACTION_SET_USER_INFO = 'ACTION_SET_USER_INFO';
const ACTION_CLEAR_USER_INFO = 'ACTION_CLEAR_USER_INFO';

export {
    CATEGORY_PAGE_URL,
    API_BASE_URL,
    HOME_PAGE_URL,
    LOGIN_PAGE_URL,
    PERSONAL_PAGE_URL,
    SIGNUP_PAGE_URL,
    ROLE_ADMIN,
    ROLE_USER,
    LOCAL_STORAGE_NAME,
    ACTION_GET_USER_INFO,
    ACTION_SET_USER_INFO,
    ACTION_CLEAR_USER_INFO,
};
